---
- name: uninstall the iis web service
  hosts: windows

  tasks:
    - name: stop iis service
      win_service:
        name: W3Svc
        state: stopped

    - name: uninstall iis
      win_feature:
        name: Web-Server
        state: absent

    - name: Create website index.html
      win_file:
        path: C:\Inetpub\wwwroot\index.html
        state: absent

    - name: Show website address
      debug:
        msg: http://{{ ansible_host }}